NumPy 数组的维数称为秩（rank），秩就是轴的数量，即数组的维度，一维数组的秩为 1，二维数组的秩为 2，以此类推。

在 NumPy中，每一个线性的数组称为是一个轴（axis），也就是维度（dimensions）。比如说，二维数组相当于是两个一维数组，其中第一个一维数组中每个元素又是一个一维数组。所以一维数组就是 NumPy 中的轴（axis），第一个轴相当于是底层数组，第二个轴是底层数组里的数组。而轴的数量——秩，就是数组的维数。

很多时候可以声明 axis。axis=0，表示沿着第 0 轴进行操作，即对每一列进行操作；axis=1，表示沿着第1轴进行操作，即对每一行进行操作。

NumPy 的数组中比较重要 ndarray 对象属性有：
| 属性             | 说明                                                                 |
|------------------|----------------------------------------------------------------------|
| ndarray.ndim     | 数组的秩（rank），即数组的维度数量或轴的数量。                         |
| ndarray.shape    | 数组的维度，表示数组在每个轴上的大小。对于二维数组（矩阵），表示其行数和列数。 |
| ndarray.size     | 数组中元素的总个数，等于 ndarray.shape 中各个轴上大小的乘积。           |
| ndarray.dtype    | 数组中元素的数据类型。                                                 |
| ndarray.itemsize | 数组中每个元素的大小，以字节为单位。                                   |
| ndarray.flags    | 包含有关内存布局的信息，如是否为 C 或 Fortran 连续存储，是否为只读等。     |
| ndarray.real     | 数组中每个元素的实部（如果元素类型为复数）。                           |
| ndarray.imag     | 数组中每个元素的虚部（如果元素类型为复数）。                           |
| ndarray.data     | 实际存储数组元素的缓冲区，一般通过索引访问元素，不直接使用该属性。       |

In [14]:
import numpy as np 
#arange(24) 是 NumPy 中用于创建等差数组的函数。它类似于 Python 内置的 range()，但返回的是一个 NumPy 数组 
# 基本说明：
# np.arange([start,] stop[, step]) 根据指定的起始值、终止值和步长生成一维数组。
# 当只传入一个参数时（如 24），该参数被视作 终止值（stop），起始值默认为 0，步长默认为 1。
# a = np.arange(24) 的具体含义：
# 生成一个从 0 开始，到 23 结束（不包含 24），步长为 1 的一维整型数组。
# 数组包含 24 个元素：[0, 1, 2, 3, ..., 23]。
# 形状为 (24,)，大小为 24，数据类型为默认的 int_（通常是 int32 或 int64，取决于平台）。
a = np.arange(24) 
print (a)
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
# a 原本是包含 0 到 23 共 24 个元素的一维数组，形状为 (24,)。
# a.reshape(2,4,3) 将总元素数量不变的数组重新组织为三个维度的大小分别为 2、4、3 的新数组。
# 第一维（轴0）：2 个块（block），每个块是一个 4×3 的矩阵。
# 第二维（轴1）：每个块中有 4 行。
# 第三维（轴2）：每行有 3 个元素。
# 返回的新数组 b 与原数组 a 共享数据内存（视图），改变 b 的元素会同时影响 a。
# 由于 2 × 4 × 3 = 24，与原始元素总数一致，所以 reshape 合法。
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b)
print (b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [5]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [10]:
import numpy as np  
 
a = np.array([[1,2,3],[4,5,6]])  
print (a)
print (a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [11]:
import numpy as np 
 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape =  (3,2)  
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
import numpy as np 
 
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


ndarray.flags 返回 ndarray 对象的内存信息，包含以下属性：

| 属性                    | 描述                                                                 |
|-------------------------|----------------------------------------------------------------------|
| C_CONTIGUOUS (C)        | 数据是在一个单一的 C 风格的连续段中                                  |
| F_CONTIGUOUS (F)        | 数据是在一个单一的 Fortran 风格的连续段中                            |
| OWNDATA (O)             | 数组拥有它所使用的内存或从另一个对象中借用它                          |
| WRITEABLE (W)           | 数据区域可以被写入，将该值设置为 False，则数据为只读                  |
| ALIGNED (A)             | 数据和所有元素都适当地对齐到硬件上                                    |
| UPDATEIFCOPY (U)        | 这个数组是其它数组的一个副本，当这个数组被释放时，原数组的内容将被更新 |
| WRITEBACKIFCOPY        | 管理数组副本与原始数据同步的标记，它是历史标记 UPDATEIFCOPY 的替代者。实现了一种 "回写" 机制，让对副本的修改能在特定时机同步回原始数。不可由用户直接通过 setflags() 设为 True。 WRITEABLE 是你的可控点：在你自己的代码里，需要关注的是 WRITEABLE 标志。它直接决定了数组当前的内容能否被修改|


In [13]:
import numpy as np 
 
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

