## 数组创建
创建数组的方法有很多种。

例如，您可以使用该array函数从普通的 Python 列表或元组创建数组。结果数组的类型由序列中元素的类型推断得出。

In [3]:
import numpy as np
a = np.array([2, 3, 4])
print (a)
b = np.array([1.2, 3.5, 5.1])
print (b)

[2 3 4]
[1.2 3.5 5.1]


通常情况下，数组的元素最初是未知的，但数组的大小是已知的。因此，NumPy 提供了一些函数来创建带有初始占位符内容的数组。这些函数最大限度地减少了扩展数组的必要性，而扩展数组是一项开销很大的操作。

函数zeros创建一个全为零的数组

函数ones创建一个全为一的数组

函数empty 创建一个初始内容随机且取决于内存状态的数组。

默认情况下，所创建数组的数据类型为 `dtype` float64，但可以通过关键字参数 `dtype` 指定dtype。

In [12]:
a = np.zeros((3, 4))
print (a)
b = np.ones((2, 3, 4), dtype=np.int16)
print (b)

c = np.empty((2, 3)) 
print ("c:",c)
print ("c:"+str(c))
print(f"c:{c}")       # 输出：c:10

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
c: [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
c:[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
c:[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [13]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print (x)

[[281479271743489 281479271743489]
 [281479271743489 281479271743489]
 [281479271743489 281479271743489]]


In [16]:
import numpy as np
 
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [17]:
import numpy as np
 
# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 0 的数组
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [1]:
import numpy as np
 
# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 
# 创建一个与 arr 形状相同的，所有元素都为 1 的数组
ones_arr = np.ones_like(arr)
print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## range
为了创建数字序列，NumPy 提供了一个arange类似于 Python 内置函数的函数range，但它返回的是一个数组。

当arange使用浮点参数时，由于浮点精度有限，通常无法预测获得的元素数量。因此，通常最好使用linspace接收所需元素数量的函数，而不是使用步长操作。

In [15]:
import numpy as np
# arange函数参数说明： [start], stop, [step], [dtype]
a = np.arange(10,30,5,int)
print (a)
a = np.arange(10,30)
print (a)
a = np.arange(30)
print (a)
 
# 设置了 dtype
x = np.arange(5, dtype =  float)  
print (x)

[10 15 20 25]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0. 1. 2. 3. 4.]



### linspace

当arange使用浮点参数时，由于浮点精度有限，通常无法预测获得的元素数量。因此，通常最好使用linspace接收所需元素数量的函数，而不是使用步长操作。

numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

|参数	|描述    |
|-------|-------|
|start	|序列的起始值|
|stop	|序列的终止值，如果endpoint为true，该值包含于数列中|
|num	|要生成的等步长的样本数量，默认为50|
|endpoint	|该值为 true 时，数列中包含stop值，反之不包含，默认是True。|
|retstep	|如果为 True 时，生成的数组中会显示间距，反之不显示。|
|dtype	|ndarray的数据类型|

In [16]:
from numpy import pi
a = np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
print (a)
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
print (x)
print (x.size)
f = np.sin(x)
print (f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

### logspace
numpy.logspace 函数用于创建一个于等比数列。格式如下：
```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```
|参数	|描述    |
|-------|--------|
|start	|序列的起始值为：base ** start|
|stop	|序列的终止值为：base ** stop。如果endpoint为true，该值包含于数列中|
|num	|要生成的等步长的样本数量，默认为50|
|endpoint	|该值为 true 时，数列中中包含stop值，反之不包含，默认是True。|
|base	|对数 log 的底数。|
|dtype	|ndarray 的数据类型|

In [22]:
import numpy as np
# 默认底数是 10
a = np.logspace(1.0,  2.0, num =  10, base = 2)  
print (a)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


## 打印数组
打印数组时，NumPy 的显示方式与嵌套列表类似，但布局如下：

最后一个轴是从左到右打印的。

倒数第二页是从上到下印刷的。

其余部分也从上到下打印，每一部分之间用空行隔开。

然后，一维数组打印为行，二维数组打印为矩阵，三维数组打印为矩阵列表。

In [22]:
a = np.arange(6)                    # 1d array
print(a)
print('-'*100)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
print('-'*100)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print ("print method 1: \n",c)
print(c)
print ("print method 2: \n",c)
print ("print method 3: \n"+str(c))
print (f"print method 4:\n:{c}")

[0 1 2 3 4 5]
----------------------------------------------------------------------------------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
----------------------------------------------------------------------------------------------------
print method 1: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
print method 2: 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
print method 3: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
print method 4:
:[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## 从已有数组创建数组
numpy.asarray 类似 numpy.array，但 numpy.asarray 参数只有三个，比 numpy.array 少两个。
```
numpy.asarray(a, dtype = None, order = None)
```
|参数	|描述    |
|-------|--------|
|a	    | 任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组 |
|dtype	| 数据类型，可选|
|order	| 可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。|

In [2]:
import numpy as np 
#将列表转换为 ndarray: 
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

[1 2 3]


In [3]:
import numpy as np 
#将元组转换为 ndarray: 
x =  (1,2,3) 
a = np.asarray(x)  
print (a)

[1 2 3]


In [7]:
import numpy as np 
#将元组列表转换为 ndarray:
x =  [(1,2,3),(4,5,6)] 
a = np.asarray(x)  
print (a)

[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np 
# 设置了 dtype 参数：
x =  [1,2,3] 
a = np.asarray(x, dtype =  float)  
print (a)

[1. 2. 3.]


### numpy.frombuffer
numpy.frombuffer 用于实现动态数组。

numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。
```
numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
```
**注意**：buffer 是字符串的时候，Python3 默认 str 是 Unicode 类型，所以要转成 bytestring 在原 str 前加上 b。
|参数	|描述    |
|-------|--------|
|buffer	|可以是任意对象，会以流的形式读入。|
|dtype	|返回数组的数据类型，可选|
|count	|读取的数据数量，默认为-1，读取所有数据。|
|offset	|读取的起始位置，默认为0。|

In [12]:
import numpy as np 
 
s =  b'Hello World' 
a = np.frombuffer(s, dtype =  'S1')  
print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


### numpy.fromiter
numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。
```
numpy.fromiter(iterable, dtype, count=-1)
```
    
|参数	|描述    |
|:-------|:--------|
|iterable	|可迭代对象 |
|dtype	    |返回数组的数据类型 |
|count	    |读取的数据数量，默认为-1，读取所有数据 |


In [14]:
import numpy as np 
 
# 使用 range 函数创建列表对象  
list=range(5)
it=iter(list)
 
# 使用迭代器创建 ndarray 
x=np.fromiter(it, dtype=float)
print(x)

[0. 1. 2. 3. 4.]
