## 基本操作
对数组进行算术运算时，运算结果会逐元素应用。运算结果会被赋值给一个新数组。


In [6]:
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print (b)
c = a - b
print (c)
print (b**2)
print (10 * np.sin(a))
print (a < 35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


与许多矩阵语言不同，NumPy 数组中的乘积运算符*是逐元素运算的。

矩阵乘法可以使用@运算符（在 Python 3.5 及更高版本中）或dot函数或方法来实现

In [11]:
import numpy as np

A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

#（Hadamard积）对应位置元素相乘，要求两个数组形状相同
# A * B = [[1*2, 1*0],
#          [0*3, 1*4]]
#       = [[2, 0],
#          [0, 4]]
print (A * B)     # elementwise product 
#按照线性代数中矩阵乘法的规则计算：结果矩阵第 i 行第 j 列的元素 = A 的第 i 行与 B 的第 j 列对应元素乘积之和。
A @ B = [[1*2 + 1*3,   1*0 + 1*4],
         [0*2 + 1*3,   0*0 + 1*4]]
      = [[2+3,   0+4],
         [0+3,   0+4]]
      = [[5, 4],
         [3, 4]]
print (A @ B )    # matrix product 矩阵乘法
#A.dot(B)	等价于 A @ B
print (A.dot(B))  # another matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


有些操作（例如 ` +=and` 和 `or` *=）是就地修改现有数组，而不是创建新数组。

In [14]:
import numpy as np

rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=np.int_)
print (a)
b = rg.random((2, 3))
print (b)
a *= 3
print (a)
b += a
print (b)
a += b  # b is not automatically converted to integer type
print (a)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

当操作不同类型的数组时，结果数组的类型与更通用或更精确的类型相对应（这种行为称为向上转型）。

In [20]:
import numpy as np
from numpy import pi

a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
print (b.dtype.name)
c = a + b
print (c)
print (c.dtype.name)
d = np.exp(c * 1j)
print (d)
print (d.dtype.name)

float64
[1.         2.57079633 4.14159265]
float64
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


许多一元运算，例如计算数组中所有元素的总和，都是作为ndarray类的方法实现的。

In [21]:
a = rg.random((2, 3))
print (a)
print (a.sum())
print (a.min())
print (a.max())

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]]
3.1057109529998157
0.027559113243068367
0.8277025938204418


默认情况下，这些操作会像处理数字列表一样处理数组，而忽略其形状。但是，通过指定axis 参数，您可以沿数组的指定轴执行操作：

In [22]:
b = np.arange(12).reshape(3, 4)
print (b)
#对二维数组而言，axis=0 表示垂直方向（跨行），axis=1 表示水平方向（跨列）。
print (b.sum(axis=0))     # sum of each column
print (b.min(axis=1))     # min of each row
print (b.cumsum(axis=1))  # cumulative sum along each row 表示在每一行内部进行累加

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


## 通用函数
NumPy 提供了一些常见的数学函数，例如 sin、cos 和 exp。在 NumPy 中，这些函数被称为“通用函数” ufunc。在 NumPy 中，这些函数对数组进行逐元素运算，并输出一个数组。

这些函数涵盖了数组操作、数学运算、统计、线性代数等多个方面，按功能分类如下：

## 📌 逻辑与比较
| 函数 | 说明 |
|------|------|
| `all` | 测试所有元素是否都为 True（或非零） |
| `any` | 测试是否存在至少一个 True（或非零）元素 |
| `where` | 根据条件返回满足条件的元素索引或值 |

## 📊 排序、搜索与计数
| 函数 | 说明 |
|------|------|
| `argmax` | 返回沿轴的最大值的索引 |
| `argmin` | 返回沿轴的最小值的索引 |
| `argsort` | 返回排序后的索引 |
| `sort` | 对数组进行排序 |
| `lexsort` | 使用多个键执行间接排序 |
| `nonzero` | 返回非零元素的索引 |
| `bincount` | 统计非负整数数组中每个值的出现次数 |

## 📈 统计与汇总
| 函数 | 说明 |
|------|------|
| `max` / `maximum` | `max`：数组最大值；`maximum`：逐元素取两个数组的最大值 |
| `min` / `minimum` | `min`：数组最小值；`minimum`：逐元素取两个数组的最小值 |
| `mean` | 算术平均值 |
| `median` | 中位数 |
| `average` | 加权平均值（可指定权重） |
| `std` | 标准差 |
| `var` | 方差 |
| `sum` | 求和 |
| `cumsum` | 累积和 |
| `cumprod` | 累积积 |
| `prod` | 所有元素的乘积 |
| `diff` | 计算离散差分 |
| `corrcoef` | 相关系数矩阵 |
| `cov` | 协方差矩阵 |

## 🔢 数学运算
| 函数 | 说明 |
|------|------|
| `ceil` | 向上取整 |
| `floor` | 向下取整 |
| `round` | 四舍五入 |
| `clip` | 将元素限制在指定区间内 |
| `conj` | 返回复数的共轭复数 |
| `invert` | 逐位取反（~运算） |
| `sqrt` | 平方根（虽然未列出但常见，含在示例中） |

## 🧮 线性代数与矩阵运算
| 函数 | 说明 |
|------|------|
| `dot` | 点积（矩阵乘法，1D/2D 均适用） |
| `vdot` | 向量点积（共轭处理） |
| `inner` | 内积 |
| `outer` | 外积 |
| `cross` | 叉积（向量积） |
| `trace` | 矩阵的迹（对角线之和） |
| `transpose` | 转置（或 `.T` 属性） |

## 🔧 数组操作与变换
| 函数 | 说明 |
|------|------|
| `apply_along_axis` | 沿指定轴应用函数 |
| `vectorize` | 将普通函数向量化（逐个元素应用） |
| `ravel` / `flatten` | 展平数组（未列出但相关） |

In [24]:
import numpy as np

B = np.arange(3)
print (B)
# np.exp(B) 对 B 的每个元素计算 e^x：
print (np.exp(B))
#np.sqrt(B)计算平方根：
print (np.sqrt(B))

C = np.array([2., -1., 4.])
#逐元素相加，要求两个数组形状相同（
print (np.add(B, C))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]
