## 索引、切片和迭代
一维数组可以像列表 和其他 Python 序列一样进行索引、切片和迭代 

In [28]:
a = np.arange(10)**3  # 创建数组 [0,1,2,...,9] 然后每个元素立方
print (a)
# 索引第3个元素（0-based），即 8
print (a[2])
# 切片索引2到4（不含5），即 [8 27 64]
print (a[2:5])
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
# 步长赋值：从开始到索引6（不含），每隔2个元素设为1000
a[:6:2] = 1000
print (a)
# 翻转数组（不修改原数组）
b =  a[::-1]
print (a)
print (b)
#遍历 a 的每个元素，并计算其立方根（1/3次幂）
for i in a:
    print(i**(1 / 3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


多维数组每个轴可以有一个索引。这些索引以元组的形式给出，并用逗号分隔。
当提供的索引数量少于坐标轴数量时，缺失的索引将被视为完整切片。

In [41]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=np.int_)
print (b)
print ('-'*100)
# 第2行、第3列的元素
print (b[2, 3])
print ('-'*100)
#取行索引从0到5(不包含5)（当前数据只有5行即所有行），列取索引第1列
print (b[0:5, 1])  # each row in the second column of b
print ('-'*100)
#第一个：表示取所有行,列取索引第1列
print (b[:, 1])    # equivalent to the previous example
print ('-'*100)
#行索引从1到3（不包含3），所有列
print (b[1:3, :])  # each column in the second and third row of b
print ('-'*100)
#
print (b[-1])  # the last row. Equivalent to b[-1, :]
print ('-'*100)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
----------------------------------------------------------------------------------------------------
23
----------------------------------------------------------------------------------------------------
[ 1 11 21 31 41]
----------------------------------------------------------------------------------------------------
[ 1 11 21 31 41]
----------------------------------------------------------------------------------------------------
[[10 11 12 13]
 [20 21 22 23]]
----------------------------------------------------------------------------------------------------
[40 41 42 43]
----------------------------------------------------------------------------------------------------


In [42]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
# 从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
点号( ...) 表示生成完整索引元组所需的冒号数量。例如，如果x是一个有 5 个轴的数组，则

x[1, 2, ...]相当于，x[1, 2, :, :, :]

x[..., 3]到和x[:, :, :, :, 3]

x[4, ..., 5, :]到。x[4, :, :, 5, :]

In [33]:
import numpy as np
 
a = np.array([[1,2,3],[3,4,5],[4,5,6]])  
print (a[...,1])   # 第2列元素
print ('-'*100)
print (a[1,...])   # 第2行元素
print ('-'*100)
print (a[...,1:])  # 第2列及剩下的所有元素
print ('-'*100)

[2 4 5]
----------------------------------------------------------------------------------------------------
[3 4 5]
----------------------------------------------------------------------------------------------------
[[2 3]
 [4 5]
 [5 6]]
----------------------------------------------------------------------------------------------------


对多维数组进行迭代是相对于第一个轴进行的：


In [ ]:
for row in b:
    print(row)