## 形状操控

改变数组的形状
数组的形状由每个轴上的元素数量决定：



In [23]:
import numpy as np
import numpy.random as rg

# 生成 3x4 的 [0,1) 随机数 → 乘10 → 向下取整 → 0~9 的整数
a = np.floor(10 * rg.random((3, 4)))
print (a)
print (a.shape)
print ('-'*100)
#返回展平的一维数组
print (a.ravel()) # returns the array, flattened
print ('-'*100)
# 重塑为 6 行 2 列（元素总数不变）
print (a.reshape(6, 2))  # returns the array with a modified shape
print ('-'*100)
# 转置（3x4 → 4x3）
print (a.T)  # returns the array, transposed
print (a.T.shape)
print ('-'*100)
# 原数组形状仍为 (3, 4)，未改变
print (a.shape)

[[7. 6. 6. 6.]
 [5. 9. 0. 0.]
 [3. 4. 9. 6.]]
(3, 4)
----------------------------------------------------------------------------------------------------
[7. 6. 6. 6. 5. 9. 0. 0. 3. 4. 9. 6.]
----------------------------------------------------------------------------------------------------
[[7. 6.]
 [6. 6.]
 [5. 9.]
 [0. 0.]
 [3. 4.]
 [9. 6.]]
----------------------------------------------------------------------------------------------------
[[7. 5. 3.]
 [6. 9. 4.]
 [6. 0. 9.]
 [6. 0. 6.]]
(4, 3)
----------------------------------------------------------------------------------------------------
(3, 4)


如果在重塑操作中指定了某个尺寸-1，则其他尺寸会自动计算：

In [24]:
a.reshape(2, -1)

array([[7., 6., 6., 6., 5., 9.],
       [0., 0., 3., 4., 9., 6.]])

**ndarray.resize函数直接修改数组本身**

In [25]:
print (a.resize(3,4))
print (a)

None
[[7. 6. 6. 6.]
 [5. 9. 0. 0.]
 [3. 4. 9. 6.]]


## 将不同的数组堆叠在一起
多个数组可以沿不同轴堆叠在一起：

In [29]:
a = np.floor(10 * rg.random((2, 2)))
print (a)
b = np.floor(10 * rg.random((2, 2)))
print (b)
#垂直堆叠
# 作用：将数组 a 和 b 按行方向（垂直）堆叠，即把 b 的行放在 a 的行下方。
# 要求：两个数组必须有相同的列数（a.shape[1] == b.shape[1]）。
# 结果形状：(a.shape[0] + b.shape[0], a.shape[1])。例如 (2,2) + (2,2) → (4,2)。
print (np.vstack((a, b)))
#水平堆叠
# 作用：将数组 a 和 b 按列方向（水平）堆叠，即把 b 的列放在 a 的列右侧。
# 要求：两个数组必须有相同的行数（a.shape[0] == b.shape[0]）。
# 结果形状：(a.shape[0], a.shape[1] + b.shape[1])。例如 (2,2) + (2,2) → (2,4)。
np.hstack((a, b))

[[3. 1.]
 [9. 2.]]
[[9. 5.]
 [3. 7.]]
[[3. 1.]
 [9. 2.]
 [9. 5.]
 [3. 7.]]


array([[3., 1., 9., 5.],
       [9., 2., 3., 7.]])

**column_stack**将一维数组作为列堆叠成一个二维数组。它等价于hstack仅适用于二维数组的函数：

In [50]:
from numpy import newaxis

a = np.floor(10 * rg.random((2, 2)))
b = np.floor(10 * rg.random((2, 2)))
print ('a:\n',a)
print ('b:\n',b)
#对于二维数组，等价于 np.hstack。
print ('二维数组column_stack：\n',np.column_stack((a, b))) # with 2D arrays
print ('-'*50)
a = np.array([4., 2.])
b = np.array([3., 8.])
print ('a:\n',a)
print ('b:\n',b)
##  将多个一维数组按列堆叠成二维。一维数组转为列向量再拼接，结果 (2,2)
print ('一维数组column_stack(转为列向量再拼接)：\n',np.column_stack((a, b)))  # returns a 2D array
print ('-'*50)
# 直接水平拼接一维数组，结果 (4,)
print ('一维数组hstack:\n',np.hstack((a, b)))        # the result is different
print ('-'*50)
#将 a 变成列向量，形状 (2,1)
#使用 newaxis 的作用
#a[:, newaxis] 将形状 (2,) 变为 (2,1)，成为列向量。
print (a[:, newaxis])  # view `a` as a 2D column vector
print (np.column_stack((a[:, newaxis], b[:, newaxis])))
print (np.hstack((a[:, newaxis], b[:, newaxis])))  # the result is the same

a:
 [[4. 7.]
 [2. 0.]]
b:
 [[7. 6.]
 [5. 8.]]
二维数组column_stack：
 [[4. 7. 7. 6.]
 [2. 0. 5. 8.]]
--------------------------------------------------
a:
 [4. 2.]
b:
 [3. 8.]
一维数组column_stack(转为列向量再拼接)：
 [[4. 3.]
 [2. 8.]]
--------------------------------------------------
一维数组hstack:
 [4. 2. 3. 8.]
--------------------------------------------------
[[4.]
 [2.]]
[[4. 3.]
 [2. 8.]]
[[4. 3.]
 [2. 8.]]


## 将一个数组拆分成几个较小的数组
|函数	|数组及操作    |
|-------|-------------|
|split	|将一个数组分割为多个子数组
|hsplit	|将一个数组水平分割为多个子数组（按列）|
|vsplit	|将一个数组垂直分割为多个子数组（按行）|


In [4]:
import numpy as np
 
harr = np.floor(10 * np.random.random((2, 6)))
print ('原array：')
print(harr)
 
print ('hsplit拆分后：')
print(np.hsplit(harr, 3))

print ('拆分后：')
print(np.vsplit(harr, 2))

原array：
[[6. 6. 5. 2. 0. 6.]
 [2. 3. 1. 1. 2. 0.]]
hsplit拆分后：
[array([[6., 6.],
       [2., 3.]]), array([[5., 2.],
       [1., 1.]]), array([[0., 6.],
       [2., 0.]])]
拆分后：
[array([[6., 6., 5., 2., 0., 6.]]), array([[2., 3., 1., 1., 2., 0.]])]
